// <auto-generated />
namespace FinancialPlannerApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MakingDatesRequiredInBudget : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakingDatesRequiredInBudget));
        
        string IMigrationMetadata.Id
        {
            get { return "201503180150406_MakingDatesRequiredInBudget"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
